### ISSUE TITLE
RUN PROGRAM

### ISSUE THREAD

**Issue by FROST03-cyber** [pranavajy/Hospital-Management-software#13]
how do i run your program ....your readme.md doesnt have the process on how one runs and installs the program

**Comment by cyblogerz** [comment]
You can run the program by simply running the `main.py` file  located under the Main folder.

**Comment by FROST03-cyber** [comment]
i have been trying that for the 100th time by running python main.py even
using python3 mai.py and it is still not working

**Comment by cyblogerz** [comment]
There might be an error at your end.

Can you send me the screenshot of the error message?

**Comment by cyblogerz** [comment]
> i have been trying that for the 100th time by running python main.py even using python3 mai.py and it is still not working
> […](#)
> On Wed, Dec 8, 2021 at 12:15 PM Pranav Ajay ***@***.***> wrote: Closed 13 <#13>. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub <[#13 (comment)](https://github.com/cyblogerz/Hospital

**Comment by cyblogerz** [comment]
Can you clone the project  again and run it, I have made some changes.

**Comment by FROST03-cyber** [comment]
Thanks a lot its working now 👍
